prod:
    stage: build
    before_script:
      - eval $(ssh-agent -s)
      - echo "$GITLAB_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - echo $REGISTRY $REGISTRY_USER $REGISTRY_PASSWORD
      - docker login $REGISTRY --username $REGISTRY_USER --password $REGISTRY_PASSWORD
    script:
      - make build-image TAG=$CI_JOB_ID REGISTRY=$REGISTRY
      - make push-image TAG=$CI_JOB_ID REGISTRY=$REGISTRY
      - source .build_info
      - ssh -o StrictHostKeyChecking=no $GOODZONE_PROD_USER@$GOODZONE_PROD_HOST 'docker service update --with-registry-auth
        --image '$REGISTRY'/'$PROJECT_NAME'/'$APP'/'$APP':'$CI_JOB_ID' '$APP''
    only:
      - master