image: docker:19.03.8

pipelines:
  branches:
    staging:
      - step:
          name: Deploy to Stating
          services:
            - docker
          script:
            - apk update && apk add make && apk add openssh
            - docker login $DELEVER_REGISTRY --username $DELEVER_DOCKER_USERNAME --password $DELEVER_DOCKER_PASSWORD
            - make build-image TAG=$BITBUCKET_BUILD_NUMBER ENV_TAG=test
            - make push-image  TAG=$BITBUCKET_BUILD_NUMBER ENV_TAG=test
            - source .build_info
            - ssh delever@$GOODZONE_PROD_HOST 'docker service update --with-registry-auth --image '$DELEVER_REGISTRY'/'$APP':'$BITBUCKET_BUILD_NUMBER' delever_'$APP''

