image: docker:19.03.8

pipelines:
  branches:
    staging:
      - step:
          name: Deploy to Stating
          services:
            - docker
          script:
            - apk update && apk add make && apk add openssh
            - docker login $REGISTRY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - make build-image TAG=$BITBUCKET_BUILD_NUMBER ENV_TAG=test
            - make push-image  TAG=$BITBUCKET_BUILD_NUMBER ENV_TAG=test
            - source .build_info
            - ssh delever@$TEST_HOST 'docker service update --with-registry-auth --image '$REGISTRY'/'$APP':'$BITBUCKET_BUILD_NUMBER' gz_'$APP''

    master:
      - step:
          name: Deploy to Prod
          services:
            - docker
          script:
            - apk update && apk add make && apk add openssh
            - docker login $REGISTRY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            - make build-image TAG=$BITBUCKET_BUILD_NUMBER REGISTRY=$REGISTRY
            - make push-image  TAG=$BITBUCKET_BUILD_NUMBER REGISTRY=$REGISTRY
            - source .build_info
            - ssh goodzone@$GOODZONE_PROD_HOST 'docker service update --with-registry-auth
              --image '$REGISTRY'/'$APP':'$BITBUCKET_BUILD_NUMBER' '$APP''

definitions:
  services:
    docker:
      memory: 3072

