export const productActionTypes = {
    GET_PRODUCTS_FROM_API: "GET_PRODUCTS_FROM_API ",
    GET_PRICES: "GET_PRICES",
    PRICE_CHANGE: "PRICE_CHANGE",
    CLEAR_PRICE_FILTER: "CLEAR_PRICE_FILTER",
};
