export const cartActionTypes = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    REDUCE_CART_ITEM_QUANTITY: "REDUCE_CART_ITEM_QUANTITY",
    CLEAR_CART: "CLEAR_CART",
    GET_PRODUCTS_FROM_API: "GET_PRODUCTS_FROM_API",
};
